apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx-alpine:latest
        imagePullPolicy: IfNotPresent
        name: nginx-alpine
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
